os:
  - linux
  - osx
language: c
compiler:
  - gcc
  - clang

addons:
  apt:
    - cppcheck
    - valgrind
    - doxygen
    - graphviz

script:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then make; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then make doxygen && make valgrind && make analysis && make clean && make test; fi
after_success:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then bash <(curl -s https://codecov.io/bash); fi
