os:
  - linux
  - osx
language: c
addons:
  - clang
install: 
  # cppcheck
  - sudo apt-get install -qq cppcheck
  - sudo apt-get install -qq valgrind
  - sudo apt-get install -qq doxygen
  - sudo apt-get install -qq graphviz
script:
  - make doxygen
  - make valgrind
  - make analysis
  - make clean
  - make test
after_success:
  - bash <(curl -s https://codecov.io/bash)
